### PR TITLE
Changing the automate datastore import validation.

### PR DESCRIPTION
**Pull request by pkomanek**
Increasing amount of checks for the automate import validation. 

Since it is not allowed to remove any automate system domain from the UI, we are removing an option to import your custom system domains into the datastore. PR also includes some refactoring of the validation checks and the error message creation logic. It is based on https://bugzilla.redhat.com/show_bug.cgi?id=1753586 and it is related to https://github.com/ManageIQ/manageiq-ui-classic/pull/6434

Diagram bellow shows the validation logic for the automate import:
Diagram

### CODE REVIEW

**Comment by gmcculloug** [comment]
@pkomanek Are you ready to remove the `WIP` flags from this PR?  
@tinaafitz Please review

**Comment by pkomanek** [comment]
@gmcculloug yes. I am still not 100% sure about the text for error messages. I am open to any opinion.

**Comment by simaishi** [comment]
@pkomanek @tinaafitz can this be `ivanchuk/yes`?

**Comment by tinaafitz** [comment]
Hi @simaishi, Yes, this can be Ivanchuk if the related UI PR can be backported: https://github.com/ManageIQ/manageiq-ui-classic/pull/6434.

**Comment by simaishi** [comment]
@tinaafitz https://github.com/ManageIQ/manageiq-ui-classic/pull/6434 can be backported to ivanchuk as well, but this PR conflicts on cherry-pick as this PR depends on https://github.com/ManageIQ/manageiq-automation_engine/pull/355 which is `ivanchuk/no`. Can you create a separate PR for ivanchuk?

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 2fe6402c889b028e532c439a03d2e3e6859e1449
Author: tina <tfitzger@redhat.com>
Date:   Wed Dec 18 11:19:57 2019 -0500

    Merge pull request #395 from pkomanek/reworking_automate_datastore_import_validation

    Changing the automate datastore import validation.

    (cherry picked from commit 8c1497c4142656643340cd0f1ec2b7232b24bda3)

    https://bugzilla.redhat.com/show_bug.cgi?id=1753586
```

**Pull request merged**
