### PR TITLE
Add dependency on rubyzip gem

### PR DESCRIPTION
**Pull request by chessbyte**
To enable https://github.com/ManageIQ/manageiq-gems-pending/pull/191

### CODE REVIEW

**Comment by gmcculloug** [comment]
@chessbyte @jrafanie Hakiri is recommending to use version 1.2.1.  With the `~>` I know that version will get pulled in anyway, but does it make sense to change it here to clear the security warning?

**Comment by jrafanie** [comment]
@gmcculloug I think so.  Let's use `~>1.2.1`

**Comment by chessbyte** [comment]
@gmcculloug @jrafanie Updated to `~>1.2.1`

**Comment by gmcculloug** [comment]
👍  Will merge when tests pass.

**Pull request merged**
