### PR TITLE
[Changelog] Update for Hammer-6

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@tinaafitz as time permits, can you review/merge.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 031f7595dae2296e68152870eb2ee7be0861bb5d
Author: tina <tfitzger@redhat.com>
Date:   Fri May 17 10:18:58 2019 -0400

    Merge pull request #325 from JPrause/hammer6_cl
    
    [Changelog] Update for Hammer-6
    
    (cherry picked from commit 4e6e847bf2fe963ad79cc8c36758a49f23f1b61a)
```

**Pull request merged**
