### PR TITLE
Edit exposed methods for Cloud Tenant

### PR DESCRIPTION
**Pull request by andyvesel**
Changed exposed raw methods to non-raw. 
The pattern is: we want to have non-raw methods on a base class, in order to expose them instead of raw methods.

### CODE REVIEW

**Comment by gmcculloug** [comment]
This PR fixes the methods exposed from the automate service model that were introduced in PR https://github.com/ManageIQ/manageiq/pull/11259.  I am changing this to a bug and label for back-porting to the same branches the original PR updated.

**Comment by simaishi** [comment]
@andyvesel Is there a BZ for this?  Can you please create one if it doesn't exist?

**Comment by andyvesel** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1451835

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 13396127f31c2c72892220c0910590575789ae63
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed May 10 08:51:15 2017 -0400

    Merge pull request #15 from andyvesel/edit_exposed_methods_for_tenant
    
    Edit exposed methods for Cloud Tenant
    (cherry picked from commit 0a87c347894455909a4f3862ebe0b43e9395be5a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1452363
```

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 44eca53da9fa941644c1881f0ac07b776361dce2
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed May 10 08:51:15 2017 -0400

    Merge pull request #15 from andyvesel/edit_exposed_methods_for_tenant
    
    Edit exposed methods for Cloud Tenant
    (cherry picked from commit 0a87c347894455909a4f3862ebe0b43e9395be5a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1459928
```

**Pull request merged**
