### PR TITLE
[Changelog] Update for Ivanchuk Beta1 release

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by JPrause** [comment]
@tinaafitz as time permits, can you review/merge.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit fae966357340ac193b0b8cf6c2d829716a7ff814
Author: tina <tfitzger@redhat.com>
Date:   Wed Jul 31 15:27:48 2019 -0400

    Merge pull request #343 from JPrause/ivanb1_cl
    
    [Changelog] Update for Ivanchuk Beta1 release
    
    (cherry picked from commit eba7127b5ee050345ae4eeccffb52c70b3f6252f)
```

**Pull request merged**
