### PR TITLE
Expose folders to ems_folder service model.

### PR DESCRIPTION
**Pull request by tinaafitz**
Expose folders for easier access.

https://bugzilla.redhat.com/show_bug.cgi?id=1637660

### CODE REVIEW

**Comment by tinaafitz** [comment]
@miq-bot add_label hammer/yes
@miq-bot assign @gmcculloug

**Comment by tinaafitz** [comment]
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit cdbcf67c26890eebe376d89c2fc5961b0f43d0db
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Oct 15 15:16:17 2018 -0400

    Merge pull request #256 from tinaafitz/expose_folder_to_emsfolder
    
    Expose folders to ems_folder service model.
    
    (cherry picked from commit 305f45fd49434ee2dab0d0402ef9a35f6fc3b1b7)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1637660
```

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 869ccd55e91cd9759667c180323a1f7c7c064cf4
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Oct 15 15:16:17 2018 -0400

    Merge pull request #256 from tinaafitz/expose_folder_to_emsfolder
    
    Expose folders to ems_folder service model.
    
    (cherry picked from commit 305f45fd49434ee2dab0d0402ef9a35f6fc3b1b7)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1640195
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit bbd32665f5e665a62ba81acf835c952444c96c28
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Oct 15 15:16:17 2018 -0400

    Merge pull request #256 from tinaafitz/expose_folder_to_emsfolder
    
    Expose folders to ems_folder service model.
    
    (cherry picked from commit 305f45fd49434ee2dab0d0402ef9a35f6fc3b1b7)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1640194
```

**Pull request merged**
