### PR TITLE
[WIP] Remove to_xml

### PR DESCRIPTION
**Pull request by d-m-u**
This is follow-up to https://github.com/ManageIQ/manageiq-automation_engine/pull/429.

This was what I could remove without specs failing, and it's kinda late, so I'll get back to it tomorrow.

there are a few more:
``` ruby
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:193:    def attribute_value_to_xml(value, xml)
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:204:            xml.Element(:index => i + 1) { attribute_value_to_xml(value[i], xml) }
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:210:            xml.Key(:name => k.to_s) { attribute_value_to_xml(v, xml) }
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:221:    def to_xml(options = {})
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:227:          xml.MiqAeAttribute(:name => k) { attribute_value_to_xml(@attributes[k], xml) }
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb:230:        children.each { |c| c.to_xml(:builder => xml) }
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb:201:        objs.each { |obj| obj.to_xml(:builder => xml) }
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb:205:    def to_xml(path = nil)
lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb:209:      XmlHash.from_hash({"MiqAeObject" => result}, {:rootname => "MiqAeWorkspace"}).to_xml.write(s, 2)
```

but with those removed as well, https://github.com/ManageIQ/manageiq-automation_engine/blob/1a3ba3a3cde0706890050e405f56b4c808213c1e/spec/miq_ae_state_machine_spec.rb#L37 fails with `ae_result` of `error` rather than `ok`.

Maybe also `app/models/miq_ae_datastore/xml_import.rb` can go, but I have to look closer at it tomorrow cause it causes ` uninitialized constant` constant problems

### CODE REVIEW

**Comment by d-m-u** [comment]
@miq-bot add_label technical debt

**Comment by gmcculloug** [comment]
@mkanoor Any concern with trying to get rid of all the XML stuff on master?  It likely needs to happen over the course of a few PRs, but feels like a good technical debt cleanup.  Thoughts?

**Comment by mkanoor** [comment]
@gmcculloug I think the UI uses this to display the output of simulation, we would have to coordinate with them to start using JSON instead of XML when displaying the simulation output.
https://github.com/ManageIQ/manageiq-ui-classic/blob/b0e5666b3d3abfa857856c4bae70759039f84c6c/app/presenters/tree_builder_automate_simulation_results.rb#L17
There might be other places in the UI. Otherwise looks good

**Comment by skateman** [comment]
The Automate->Simulation in the UI depends on the `to_xml` method as the simulation results can be displayed as XML and the tree view is being built by parsing the same XML. I can try to build the tree directly from the result object, but it doesn't really help if we don't get rid of the XML view.

Screenshot-from-2020-03-11-11-15-10

**Comment by gmcculloug** [comment]
@skateman I see little use for the `XML View` tab so I feel it is safe to remove.  @mkanoor Do we have the methods to support building the `Tree View` from YAML or JSON?

**Comment by skateman** [comment]
@gmcculloug we don't really need the YAML or JSON version, I can just build the tree directly from the objects. Faster to build directly and avoid parsing of formats...

**Comment by d-m-u** [comment]
there's also `to_expanded_xml` which I'm not sure if I can remove or not because we use it in ```miq_log_workspace(obj, _inputs)``` inside miq_ae_builtin_method

**Comment by skateman** [comment]
That's the one I'm dependent on in the UI, but it's getting close...

**Comment by d-m-u** [comment]
gotcha, thanks

**Comment by skateman** [comment]
I'm blocked by https://github.com/ManageIQ/manageiq-automation_engine/issues/418 but @jrafanie is working on it

**Comment by d-m-u** [comment]
it's fine, this's got that failing spec that i'm looking into, there's no rush

**Comment by skateman** [comment]
Orienting in the code is way too complicated for me, so maybe @mkanoor's idea about you implementing a `to_json` version isn't that bad...if you can.

**Comment by lfu** [comment]
How about [xml_import](https://github.com/ManageIQ/manageiq-automation_engine/blob/ee70c81750d70c7e25a992b638b619b09868b70b/app/models/miq_ae_datastore/xml_import.rb#L2)? Do we not remove it this time?

**Comment by djberg96** [comment]
@skateman, @lfu is the baked in Rails method something we could use?

https://apidock.com/rails/Hash/to_xml

**Pull request closed without merging**
