### PR TITLE
Add helper method #create_job for Ansible Tower Job/Workflow template.

### PR DESCRIPTION
**Pull request by lfu**
To run Ansible Tower workflow template from a custom button.

Blocks https://github.com/ManageIQ/manageiq-content/pull/490
https://bugzilla.redhat.com/show_bug.cgi?id=1658172

### CODE REVIEW

**Comment by lfu** [comment]
@miq-bot add_label bug, hammer/yes

**Comment by lfu** [comment]
@tinaafitz @mkanoor @gmcculloug Please review.

**Comment by tinaafitz** [comment]
@mkanoor Please review

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 0bc32634a8521ed82373e48f940c75f2ad33b98b
Author: tina <tina.fitzgerald2@gmail.com>
Date:   Thu Apr 18 13:35:13 2019 -0400

    Merge pull request #283 from lfu/launch_ansible_job_with_template_1658172
    
    Add helper method #create_job for Ansible Tower Job/Workflow template.
    
    (cherry picked from commit b5c33c5e5b3cca034a73a5c74c4cfa7860309027)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1763859
```

**Pull request merged**
