### PR TITLE
Fix automation array values

### PR DESCRIPTION
**Pull request by GilbertCherrie**
Fixed automation array values for multi select drop downs in Order Service Forms.

When ordering from a Service Catalog for an Ansible Playbook Catalog Item there is a bug with multi-select dropdown values not being correctly sent to the Ansible Playbook.

An example order service form with a multi-select dropdown:
Screenshot 2024-04-22 at 3 38 28 PM

Before:
When viewing the Ansible Playbook output in the Services / My Services Screen for the Service you order will look like this. `test1` is the multi-select dropdown value and it outputs "VARIABLE IS NOT DEFINED!". `test2` is just a single select dropdown used for reference.
Screenshot 2024-04-22 at 3 38 11 PM

This is due to the field being with "Array::" on its key value causing the Ansible Playbook output to not be able to find that variable. When the "Array::" tag is removed from the key it then displays the Array as a String with `\u001f` separating the Array items.
Screenshot 2024-04-22 at 3 47 51 PM

After:
By removing the "Array::" tag from the variable key as well as converting the value being sent to the Ansible Playbook from a String to an Array we receive the Array in the Playbook and see it on the Playbook output correctly. This allows us to send Arrays to the Ansible Playbook and view it correctly on the output screen as individual items instead of as a String.
Screenshot 2024-04-22 at 3 30 43 PM

### CODE REVIEW

**Comment by GilbertCherrie** [comment]
Need a ui fix for this: https://github.com/ManageIQ/manageiq-ui-classic/commit/3cdd0071706173fdc6b55858b985bd614f6dc362

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `radjabov` in commit f74123ed477ea5da5ef995ce33a8cc0f1b270bdc.

```text
commit f74123ed477ea5da5ef995ce33a8cc0f1b270bdc
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Jun 28 17:12:11 2024 -0400

    Merge pull request #545 from GilbertCherrie/fix_automation_arrays
    
    Fix automation array values
    
    (cherry picked from commit 7707684565508d02dcc2345b4f706c0f885ea620)
```

**Comment by Fryguy** [comment]
Reverted backport to `radjabov` via 626df0441c7cc95c86c9ee4ee1ba0f667df7898a

**Comment by Fryguy** [comment]
Reverted via 1ef49fbba0290ed95d57a71bb5436c4e45a16cc6

```
commit 1ef49fbba0290ed95d57a71bb5436c4e45a16cc6 (HEAD -> master, upstream/master, upstream/HEAD)
Author: Jason Frey <fryguy9@gmail.com>
Date:   Mon Nov 4 14:49:00 2024 -0500

    Revert "Merge pull request #545 from GilbertCherrie/fix_automation_arrays"

    This reverts commit 7707684565508d02dcc2345b4f706c0f885ea620, reversing
    changes made to ac85c9f1eb74c97b79de3c935fd232c4614bca26.
```

**Pull request merged**
