### PR TITLE
Expose supports_vm_import? instead of validate_import_vm

### PR DESCRIPTION
**Pull request by smelamud**
Depends-on: https://github.com/ManageIQ/manageiq/pull/16526

### CODE REVIEW

**Comment by smelamud** [comment]
@miq-bot assign gmcculloug

**Comment by smelamud** [comment]
Rubocop warning is false, expose is called without parentheses everywhere.

**Comment by gmcculloug** [comment]
Tested locally with related PR https://github.com/ManageIQ/manageiq-content/pull/218.

@bdunne This PR is not running travis tests.  Any idea why?  Same for related PR in content repo.

**Comment by bdunne** [comment]
@gmcculloug Maybe Travis missed the hook?  It happens once in a while.  Usually I close and reopen the PR to trigger it again.

**Comment by smelamud** [comment]
@miq-bot add_labels gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit db3b444c88f3f1dc7d9aac0dcf0b4b682aa7c1d7
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Nov 27 22:22:41 2017 -0500

    Merge pull request #121 from smelamud/supports-vm-import
    
    Expose supports_vm_import? instead of validate_import_vm
    (cherry picked from commit f80c97b6df2249500ebd7a93a6dcc42708f083d7)
```

**Pull request merged**
