### PR TITLE
Rubocop run with `--fix-layout` option.

### PR DESCRIPTION
**Pull request by gmcculloug**
Run only layout cops: `rubocop -a -x `

```ruby
Usage: rubocop [options] [file1, file2, ...]
  -a, --auto-correct               Auto-correct offenses.
  -x, --fix-layout                 Run only layout cops, with auto-correct on.
```

### CODE REVIEW

**Comment by gmcculloug** [comment]
Marking as WIP for now.  Along with resolving conflicts I'm going to pull the `find_by_*` changes out of this PR and into a separate one.  Not all are correct as some have custom `find_by_*` methods on the classes so need to address that as well.  I have been talking to a few people about renaming the existing `find_by_` methods in the main repo to avoid this confusion.

**Comment by lfu** [comment]
Please address Travis failure. Otherwise it looks good.

**Comment by gmcculloug** [comment]
@lfu @tinaafitz Finally got back to rebase and cleanup this PR.  As this is mostly all layout changes (see few exceptions below) you might want to review using the "Hide whitespace changes" option to reduce the amount of file changes in the diff.  There is a github UI option for it on the "Files changed" tab under the gear icon:
image

Or use the following link: https://github.com/ManageIQ/manageiq-automation_engine/pull/362/files?w=1


Exceptions to the layout change are
1. Perfer `if` over `unless` in `lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_path.rb`:
```diff
-    parts_array << @ae_attribute    unless @ae_attribute.blank?
+    parts_array << @ae_attribute if @ae_attribute.present?
```

2. Change to use `squiggly heredoc` (See [How To Use Heredoc in Ruby])(https://www.rubyguides.com/2018/11/ruby-heredoc/) here:
    * spec/models/miq_ae_datastore/xml_export_spec.rb
    * spec/service_models/miq_ae_service_service_spec.rb

I will deal with the `find_by` and `URI.unescape` rubocop issues in a separate PR.

**Comment by lfu** [comment]
Please remove `WIP` from the title.

**Comment by gmcculloug** [comment]
@tinaafitz bump

**Pull request merged**
