### PR TITLE
Expose RHV import methods to automate

### PR DESCRIPTION
**Pull request by matobet**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1404920

Depends on https://github.com/ManageIQ/manageiq-providers-ovirt/pull/21

### CODE REVIEW

**Comment by matobet** [comment]
@miq-bot add_label fine/yes

**Comment by matobet** [comment]
@miq-bot assign @gmcculloug

**Comment by matobet** [comment]
@gmcculloug I'm a bit confused about the above checkstyle error... These names were taken from the original service model classes as were defined in the core repo. Have the naming standards changed since?

**Comment by matobet** [comment]
@tinaafitz @gmcculloug could you please review?

**Comment by tinaafitz** [comment]
@matobet Looks good.

**Comment by matobet** [comment]
@tinaafitz @gmcculloug @bdunne Ok the dependent provider PR https://github.com/ManageIQ/manageiq-providers-ovirt/pull/21/ has been merged, so if there are no objections I guess we can merge this?

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit e74f58e7690935110b378f9d9cd6afd7aab91bb3
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu May 18 10:24:00 2017 -0400

    Merge pull request #4 from matobet/v2v-rhv-expose
    
    Expose RHV import methods to automate
    (cherry picked from commit 652ebbc6526f073a2e760977ec52a2b1f366c513)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1459996
```

**Pull request merged**
