### PR TITLE
[WIP]Changed substitution for non-string datatypes.

### PR DESCRIPTION
**Pull request by tinaafitz**
Changed substitute_value method to take datatype, and return subst value unless string datatype. 
Modified method calls to reflect datatype change and modified convert_value_based_on_datatype to return value if kind of service model.

### CODE REVIEW

**Comment by gmcculloug** [comment]
@tinaafitz What's the plan for this WIP PR?

**Comment by tinaafitz** [comment]
@gmcculloug I'm going to close this PR for now.  Substitution will work properly for VMDB objects if the object id is specified in the substitution string.
This PR was intended to resolve the issue where a substitution string of ${/#object} with datatype object, returns the object name, not the object.
The work around is to specify the object id as follows: ${/#object.id}

**Comment by tinaafitz** [comment]
Reopened per conversation with @mkanoor.

**Comment by tinaafitz** [comment]
Closing PR for now

**Pull request closed without merging**
