### PR TITLE
Remove check for nil zone during MiqQueue.put of GenericMailer

### PR DESCRIPTION
**Pull request by gmcculloug**
Required after changes from PR https://github.com/ManageIQ/manageiq/pull/18041 

https://bugzilla.redhat.com/show_bug.cgi?id=1629945

### CODE REVIEW

**Comment by gmcculloug** [comment]
Should get upstream and hammer tests back to green.

cc @simaishi

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit e8b937a19a727a64083b4a7424c17084bbaad070
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Tue Oct 2 15:35:56 2018 -0400

    Merge pull request #241 from gmcculloug/remove_nil_zone_check
    
    Remove check for nil zone during MiqQueue.put of GenericMailer
    
    (cherry picked from commit 1a1b0a03ca14ae8a230dc473a14c8003076871a6)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1629945
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit f9a4af879e79f27c945e724ad77a4791e6674ee3
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Tue Oct 2 15:35:56 2018 -0400

    Merge pull request #241 from gmcculloug/remove_nil_zone_check
    
    Remove check for nil zone during MiqQueue.put of GenericMailer
    
    (cherry picked from commit 1a1b0a03ca14ae8a230dc473a14c8003076871a6)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1635255
```

**Comment by simaishi** [comment]
Correctly backported in https://github.com/ManageIQ/manageiq-automation_engine/pull/267

**Pull request merged**
