### PR TITLE
Add missing service model change for calculating active quota counts for Service requests.

### PR DESCRIPTION
**Pull request by tinaafitz**
Added miq_provision_quota mixin include to Service Template Provision Request Service model.

Recently added the ability to calculate active quota counts for Service and VM requests. Missing include results in Service requests getting undefined error while running check_quota() method.
 
https://bugzilla.redhat.com/show_bug.cgi?id=1491409

Original ticket/PR to add active quota calculations modify prov methods. 
https://bugzilla.redhat.com/show_bug.cgi?id=1456819
https://github.com/ManageIQ/manageiq/pull/15466

### CODE REVIEW

**Comment by tinaafitz** [comment]
@miq-bot add_label bug, fine/yes, provisioning

**Comment by tinaafitz** [comment]
@mkanoor Please review.

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 1bc5eb462244e74babd3eadea088be3650316438
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Thu Sep 14 16:01:47 2017 -0400

    Merge pull request #69 from tinaafitz/add_quota_mixin
    
    Add missing service model change for calculating active quota counts for Service requests.
    (cherry picked from commit ca32a7918cd0e9a5664e5eb4b44d9b11458037e6)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1493207
```

**Comment by tinaafitz** [comment]
@miq-bot add_label euwe/yes

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit fd5829a15f16551a99e01664000e7719f82db842
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Thu Sep 14 16:01:47 2017 -0400

    Merge pull request #69 from tinaafitz/add_quota_mixin
    
    Add missing service model change for calculating active quota counts for Service requests.
    (cherry picked from commit ca32a7918cd0e9a5664e5eb4b44d9b11458037e6)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1492158
```

**Pull request merged**
