### PR TITLE
Bug with handling of Arrays in Automate #480

### PR DESCRIPTION
**Pull request by akhilkr128**
This PR aims to fix the issue - https://github.com/ManageIQ/manageiq-automation_engine/issues/480

**backport:** also include https://github.com/ManageIQ/manageiq/pull/21520

After the change- 
Screenshot 2021-10-13 at 6 42 34 PM

After spending lots of hours on regex to match the scenarios of wrapping special characters around the option values, I came to sense. I realized that array elements could be stored and retrieved with this small change without worrying about the special characters.

### CODE REVIEW

**Comment by akhilkr128** [comment]
No spec changes are needed for this change.

**Comment by akhilkr128** [comment]
> Can you please also add a spec demonstrating that this fixes the problem from the issue? (i.e. a string with embedded commas)?
Sure

**Comment by Fryguy** [comment]
Found one minor thing, but overall LGTM.

**Comment by Fryguy** [comment]
Backported to `morphy` in commit 3bdae46d7efd464a22409df617e969fb160d5b58.

```text
commit 3bdae46d7efd464a22409df617e969fb160d5b58
Author: Jason Frey <fryguy9@gmail.com>
Date:   Mon Oct 25 09:50:50 2021 -0400

    Merge pull request #484 from akhilkr128/multi_select_array_bug
    
    Bug with handling of Arrays in Automate #480
    
    (cherry picked from commit c75b6f543cb973772f5097ac12235c81fd4d7fdb)
```

**Pull request merged**
