### PR TITLE
Adjust Travis postgresql from 9.4 to 9.5

### PR DESCRIPTION
**Pull request by tinaafitz**
From 9.4 to 9.5 to fix test failures.

### CODE REVIEW

**Comment by tinaafitz** [comment]
@miq-bot add_label hammer/yes
@miq-bot assign @gmcculloug

**Comment by tinaafitz** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 0398ae0e5bcc91ad8de0dc4cff1fc68bc91032a8
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Oct 15 14:09:34 2018 -0400

    Merge pull request #257 from tinaafitz/adjust_postgres
    
    Adjust Travis postgresql from 9.4 to 9.5
    
    (cherry picked from commit 85d37d857b4f824811de9bf69fdbe56064698f05)
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 122799c8d5ee9d09a7318de5228f50f482516deb
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Oct 15 14:09:34 2018 -0400

    Merge pull request #257 from tinaafitz/adjust_postgres
    
    Adjust Travis postgresql from 9.4 to 9.5
    
    (cherry picked from commit 85d37d857b4f824811de9bf69fdbe56064698f05)
```

**Pull request merged**
